### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mai1015** [os-js/OS.js-development#2]
An unexpected error occured when I try to create the project.

`
2017-01-11T03:40:52.309Z Error creating directory: Error: ENOENT: no such file or directory, mkdir '/home/ubuntu/workspace/vfs/home/mai1015/.packages/MyApp' <no stack trace>`
`
2017-01-11T03:40:52.415Z <undefined error> <no stack trace>
An uncaught exception occured [Error: write after end]
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:430:15)
    at _raw (/home/ubuntu/workspace/src/server/node/core/http.js:325:14)
    at Object.freeze.json (/home/ubuntu/workspace/src/server/node/core/http.js:405:7)
    at _rejectResponse (/home/ubuntu/workspace/src/server/node/core/http.js:181:20)
    at process._tickCallback (node.js:369:9)
`

Any idea?

**Comment by andersevenrud** [comment]
It might just be because the ".packages" directory inside your homedir does not exist.

I've been a bit busy this week, but I'll check it out tomorrow :)

**Comment by andersevenrud** [comment]
It is definitely because that directory is missing. I'll make it so that it is created upon request to avoid this problem.

**Comment by andersevenrud** [comment]
I think this was solved by an update to the core today. Directories should be created recursively now.
